### ISSUE TITLE
Mono Support

### ISSUE THREAD

**Issue by DerpMeister360** [TrevTV/MelonLoader-AudioTools#2]
Could we please get Mono support in the near future? That way we can use this with other Unity games besides Boneworks/BoneLab/other IL2CPP games. Especially since it seems like in most cases, Mono is more commonly used.

**Comment by TrevTV** [comment]
If I remember right, it works fine on Mono if you compile it with the game's references instead of the IL2CPP stuff

**Comment by DerpMeister360** [comment]
Is there a tutorial for that?

**Comment by TrevTV** [comment]
No
