### ISSUE TITLE
Replaced music restarts when you move

### ISSUE THREAD

**Issue by notironicallycasters** [TrevTV/MelonLoader-AudioTools#3]
Replaced music restarts whenever i move like 10 meters away in an area where its the same music

Video demonstrating the bug in BONELAB modding server 
https://discord.com/channels/563139253542846474/724595991675797554/1272522128847278160

**Comment by TrevTV** [comment]
AudioReplacer does nothing specific to BONELAB and that's likely an issue with how their zoning system handles audio. Your song likely just doesn't work well with audio loops/changes that the BONELAB audio is designed for.

**Comment by notironicallycasters** [comment]
So if i make a code mod that changes Bonelab’s audio zoning it will be fixed ?
